version = 0.1
[default.deploy.parameters]
stack_name = "chatbot-bedrock-dynamodb-lambda-langchain"
resolve_s3 = true
s3_prefix = "chatbot-bedrock-dynamodb-lambda-langchain"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
